#include "FirebaseAuth.h"

#include <windows.h>
#include <winhttp.h>

#include <vector>
#include <stdexcept>

#pragma comment(lib, "winhttp.lib")

namespace
{
    std::wstring Utf8ToWide(const std::string& value)
    {
        if (value.empty())
            return {};

        const int size = MultiByteToWideChar(
            CP_UTF8,
            0,
            value.data(),
            static_cast<int>(value.size()),
            nullptr,
            0
        );

        if (size <= 0)
            return {};

        std::wstring result(size, L'\0');

        MultiByteToWideChar(
            CP_UTF8,
            0,
            value.data(),
            static_cast<int>(value.size()),
            result.data(),
            size
        );

        return result;
    }

    std::string WideToUtf8(const std::wstring& value)
    {
        if (value.empty())
            return {};

        const int size = WideCharToMultiByte(
            CP_UTF8,
            0,
            value.data(),
            static_cast<int>(value.size()),
            nullptr,
            0,
            nullptr,
            nullptr
        );

        if (size <= 0)
            return {};

        std::string result(size, '\0');

        WideCharToMultiByte(
            CP_UTF8,
            0,
            value.data(),
            static_cast<int>(value.size()),
            result.data(),
            size,
            nullptr,
            nullptr
        );

        return result;
    }

    std::string GetLastErrorString()
    {
        const DWORD error = GetLastError();

        if (error == ERROR_SUCCESS)
            return {};

        LPWSTR buffer = nullptr;

        const DWORD length = FormatMessageW(
            FORMAT_MESSAGE_ALLOCATE_BUFFER |
            FORMAT_MESSAGE_FROM_SYSTEM |
            FORMAT_MESSAGE_IGNORE_INSERTS,
            nullptr,
            error,
            0,
            reinterpret_cast<LPWSTR>(&buffer),
            0,
            nullptr
        );

        std::string result;

        if (length && buffer)
        {
            result = WideToUtf8(
                std::wstring(buffer, length)
            );

            LocalFree(buffer);
        }

        if (result.empty())
            result = "WinHTTP error: " + std::to_string(error);

        return result;
    }
}

FirebaseAuth::FirebaseAuth(std::string apiKey)
    : m_apiKey(std::move(apiKey))
{
    if (m_apiKey.empty())
        throw std::invalid_argument(
            "Firebase API key cannot be empty."
        );
}

FirebaseAuth::~FirebaseAuth()
{
    Logout();
}

FirebaseAuth::Result FirebaseAuth::Login(
    const std::string& email,
    const std::string& password)
{
    // Never leave a token from an earlier successful login available when a
    // later login attempt fails.
    Logout();

    Result result;

    if (email.empty() || password.empty())
    {
        result.error = "Email and password cannot be empty.";
        return result;
    }

    json requestBody =
    {
        {"email", email},
        {"password", password},
        {"returnSecureToken", true}
    };

    const std::string url =
        "https://identitytoolkit.googleapis.com/"
        "v1/accounts:signInWithPassword?key=" +
        UrlEncode(m_apiKey);

    // Send the authentication request.
    result = Request(
        url,
        requestBody.dump()
    );

    // Firebase returns an HTTP error when authentication fails.
    if (!result.success)
    {
        try
        {
            const json errorResponse =
                json::parse(result.rawResponse);

            const std::string firebaseError =
                errorResponse["error"].value(
                    "message",
                    ""
                );

            // Don't expose whether the email exists or whether the
            // password specifically was incorrect.
            if (firebaseError == "INVALID_LOGIN_CREDENTIALS" ||
                firebaseError == "EMAIL_NOT_FOUND" ||
                firebaseError == "INVALID_PASSWORD" ||
                firebaseError == "INVALID_EMAIL" ||
                firebaseError == "USER_DISABLED"
                )
            {
                result.error =
                    "Invalid username or password.";
            }
            else if (!firebaseError.empty())
            {
                // Firebase returned a different known error.
                result.error = firebaseError;
            }
        }
        catch (const std::exception&)
        {
            // The response wasn't valid JSON.
            // Keep the original error generated by Request().
        }

        return result;
    }

    // Authentication succeeded. Parse the successful Firebase response.
    try
    {
        const json response =
            json::parse(result.rawResponse);

        m_idToken =
            response.value("idToken", "");

        m_refreshToken =
            response.value("refreshToken", "");

        m_uid =
            response.value("localId", "");

        m_email =
            response.value("email", "");

        if (m_idToken.empty() || m_uid.empty())
        {
            // The HTTP request succeeded, but the authentication response
            // didn't contain the information we require.
            result.success = false;
            result.error =
                "Firebase authentication response did not "
                "contain an ID token or UID.";

            // Don't leave partially populated authentication state behind.
            Logout();
        }
    }
    catch (const std::exception& e)
    {
        result.success = false;
        result.error =
            std::string(
                "Invalid Firebase authentication response: "
            ) + e.what();

        // Make sure no partial authentication state remains.
        Logout();
    }

    return result;
}

const std::string& FirebaseAuth::GetIdToken() const
{
    return m_idToken;
}

const std::string& FirebaseAuth::GetRefreshToken() const
{
    return m_refreshToken;
}

const std::string& FirebaseAuth::GetUid() const
{
    return m_uid;
}

const std::string& FirebaseAuth::GetEmail() const
{
    return m_email;
}

bool FirebaseAuth::IsAuthenticated() const
{
    return !m_idToken.empty();
}

void FirebaseAuth::SecureWipe(std::string& value)
{
    if (!value.empty())
        SecureZeroMemory(value.data(), value.size());

    value.clear();
}

void FirebaseAuth::Logout()
{
    SecureWipe(m_idToken);
    SecureWipe(m_refreshToken);
    SecureWipe(m_uid);
    SecureWipe(m_email);
}

FirebaseAuth::Result FirebaseAuth::Request(
    const std::string& url,
    const std::string& body)
{
    Result result;

    URL_COMPONENTS components{};
    components.dwStructSize = sizeof(components);

    wchar_t hostName[256]{};
    wchar_t urlPath[4096]{};
    wchar_t extraInfo[4096]{};

    components.lpszHostName = hostName;
    components.dwHostNameLength =
        static_cast<DWORD>(std::size(hostName));

    components.lpszUrlPath = urlPath;
    components.dwUrlPathLength =
        static_cast<DWORD>(std::size(urlPath));

    components.lpszExtraInfo = extraInfo;
    components.dwExtraInfoLength =
        static_cast<DWORD>(std::size(extraInfo));

    const std::wstring wideUrl =
        Utf8ToWide(url);

    if (!WinHttpCrackUrl(
        wideUrl.c_str(),
        static_cast<DWORD>(wideUrl.size()),
        0,
        &components))
    {
        result.error = GetLastErrorString();
        return result;
    }

    HINTERNET session = WinHttpOpen(
        L"FirebaseAuth/1.0",
        WINHTTP_ACCESS_TYPE_DEFAULT_PROXY,
        WINHTTP_NO_PROXY_NAME,
        WINHTTP_NO_PROXY_BYPASS,
        0
    );

    if (!session)
    {
        result.error = GetLastErrorString();
        return result;
    }

    // Require TLS 1.2 or 1.3 — don't let WinHTTP fall back to older protocols.
    DWORD secureProtocols =
        WINHTTP_FLAG_SECURE_PROTOCOL_TLS1_2 |
        WINHTTP_FLAG_SECURE_PROTOCOL_TLS1_3;

    WinHttpSetOption(
        session,
        WINHTTP_OPTION_SECURE_PROTOCOLS,
        &secureProtocols,
        sizeof(secureProtocols)
    );

    // Bound how long we'll wait at each stage of the request.
    WinHttpSetTimeouts(
        session,
        5000,   // resolve
        5000,   // connect
        10000,  // send
        10000   // receive
    );

    HINTERNET connection = WinHttpConnect(
        session,
        components.lpszHostName,
        components.nPort,
        0
    );

    if (!connection)
    {
        result.error = GetLastErrorString();
        WinHttpCloseHandle(session);
        return result;
    }

    std::wstring requestPath =
        components.lpszUrlPath;

    if (components.lpszExtraInfo &&
        components.dwExtraInfoLength > 0)
    {
        requestPath += components.lpszExtraInfo;
    }

    DWORD flags = 0;

    if (components.nScheme == INTERNET_SCHEME_HTTPS)
        flags |= WINHTTP_FLAG_SECURE;

    HINTERNET request = WinHttpOpenRequest(
        connection,
        L"POST",
        requestPath.c_str(),
        nullptr,
        WINHTTP_NO_REFERER,
        WINHTTP_DEFAULT_ACCEPT_TYPES,
        flags
    );

    if (!request)
    {
        result.error = GetLastErrorString();

        WinHttpCloseHandle(connection);
        WinHttpCloseHandle(session);

        return result;
    }

    const wchar_t* headers =
        L"Content-Type: application/json; charset=utf-8\r\n"
        L"Accept: application/json\r\n";

    if (!WinHttpSendRequest(
        request,
        headers,
        static_cast<DWORD>(-1L),
        const_cast<char*>(body.data()),
        static_cast<DWORD>(body.size()),
        static_cast<DWORD>(body.size()),
        0))
    {
        result.error = GetLastErrorString();

        WinHttpCloseHandle(request);
        WinHttpCloseHandle(connection);
        WinHttpCloseHandle(session);

        return result;
    }

    if (!WinHttpReceiveResponse(
        request,
        nullptr))
    {
        result.error = GetLastErrorString();

        WinHttpCloseHandle(request);
        WinHttpCloseHandle(connection);
        WinHttpCloseHandle(session);

        return result;
    }

    DWORD statusCode = 0;
    DWORD statusSize = sizeof(statusCode);

    WinHttpQueryHeaders(
        request,
        WINHTTP_QUERY_STATUS_CODE |
        WINHTTP_QUERY_FLAG_NUMBER,
        WINHTTP_HEADER_NAME_BY_INDEX,
        &statusCode,
        &statusSize,
        WINHTTP_NO_HEADER_INDEX
    );

    result.httpStatus =
        static_cast<long>(statusCode);

    std::string response;

    for (;;)
    {
        DWORD available = 0;

        if (!WinHttpQueryDataAvailable(
            request,
            &available))
        {
            result.error = GetLastErrorString();
            break;
        }

        if (available == 0)
            break;

        std::vector<char> buffer(
            available
        );

        DWORD downloaded = 0;

        if (!WinHttpReadData(
            request,
            buffer.data(),
            available,
            &downloaded))
        {
            result.error = GetLastErrorString();
            break;
        }

        response.append(
            buffer.data(),
            downloaded
        );
    }

    result.rawResponse =
        std::move(response);

    result.success =
        result.error.empty() &&
        statusCode >= 200 &&
        statusCode < 300;

    if (!result.success &&
        result.error.empty())
    {
        result.error =
            "Firebase Auth HTTP error " +
            std::to_string(statusCode);

        if (!result.rawResponse.empty())
            result.error +=
            ": " + result.rawResponse;
    }

    WinHttpCloseHandle(request);
    WinHttpCloseHandle(connection);
    WinHttpCloseHandle(session);

    return result;
}

std::string FirebaseAuth::UrlEncode(
    const std::string& value)
{
    static constexpr char hex[] =
        "0123456789ABCDEF";

    std::string result;

    for (unsigned char c : value)
    {
        const bool safe =
            (c >= 'a' && c <= 'z') ||
            (c >= 'A' && c <= 'Z') ||
            (c >= '0' && c <= '9') ||
            c == '-' ||
            c == '_' ||
            c == '.' ||
            c == '~';

        if (safe)
        {
            result += static_cast<char>(c);
        }
        else
        {
            result += '%';
            result += hex[(c >> 4) & 0x0F];
            result += hex[c & 0x0F];
        }
    }

    return result;
}